"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.x
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Cargar variables de entorno desde .env (si existe)
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# -------------------------
# Básico / Entorno
# -------------------------
SECRET_KEY = os.getenv("SECRET_KEY", "dev-unsafe")  # en prod, ponelo en .env
DEBUG = os.getenv("DEBUG", "True") == "True"
ALLOWED_HOSTS = ['127.0.0.1', 'infinitocapacitaciones.com', 'www.infinitocapacitaciones.com']

# -------------------------
# Apps
# -------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Nuestra app
    'lms',
]

# -------------------------
# Middleware
# -------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = [
    "lms.backends.EmailOrUsernameBackend",
    "django.contrib.auth.backends.ModelBackend",
]

ROOT_URLCONF = 'core.urls'

# -------------------------
# Templates
# -------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # importante para que tome templates globales como registration/login.html
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,     # carga lms/templates/...
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'

# -------------------------
# Base de datos (SQLite dev)
# -------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# -------------------------
# Password validators
# -------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# -------------------------
# Internacionalización
# -------------------------
LANGUAGE_CODE = 'es-ar'  # podés dejar 'en-us' si preferís
TIME_ZONE = 'America/Argentina/Buenos_Aires'
USE_I18N = True
USE_TZ = True

# -------------------------
# Static
# -------------------------
# IMPORTANTE: con la barra inicial para que genere URLs absolutas (/static/...)
STATIC_URL = '/static/'
# En producción, configurá STATIC_ROOT y usá collectstatic
STATIC_ROOT = '/home/infinito_produccion/staticfiles'
# (opcional en dev)
# STATICFILES_DIRS = [BASE_DIR / 'static']

# -------------------------
# Media (archivos subidos por usuarios:
# avatares, comprobantes de transferencia, etc.)
# -------------------------
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# -------------------------
# Auth redirects (login/logout)
# -------------------------
LOGIN_URL = 'login'              # /login/ de django.contrib.auth.urls
LOGIN_REDIRECT_URL = 'lms:home'  # a dónde ir después de loguear
LOGOUT_REDIRECT_URL = 'lms:home' # a dónde ir después de salir

# -------------------------
# Email (activación de cuenta)
# En desarrollo: imprime los mails en consola.
# En producción: cambiá EMAIL_BACKEND y credenciales SMTP.
# -------------------------



EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = "capacitacionesinfinito@gmail.com"
EMAIL_HOST_PASSWORD = "upig hakj kthn gurm"

DEFAULT_FROM_EMAIL = "Infinito Capacitaciones <capacitacionesinfinito@gmail.com>"
SERVER_EMAIL = DEFAULT_FROM_EMAIL
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
CSRF_TRUSTED_ORIGINS = ["https://infinitocapacitaciones.com", "https://www.infinitocapacitaciones.com"]
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True

# Ejemplo de configuración SMTP para prod (descomentá y setea variables):
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
# EMAIL_PORT = int(os.getenv('EMAIL_PORT', 587))
# EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
# EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
# EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
# EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False') == 'False'

# -------------------------
# Default PK
# -------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# -------------------------
# Mercado Pago
# -------------------------
MP_ACCESS_TOKEN = os.getenv("MP_ACCESS_TOKEN", "")
MP_PUBLIC_KEY   = os.getenv("MP_PUBLIC_KEY", "")
MP_WEBHOOK_URL  = os.getenv("MP_WEBHOOK_URL", "")
MP_SUCCESS_URL  = os.getenv("MP_SUCCESS_URL", "")
# Permite que el navegador envíe al menos el ORIGIN como referer a sitios externos (YouTube)
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"




