# Generated by Django 4.2.23 on 2025-11-19 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_remove_course_created_at_remove_course_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
