# Generated by Django 4.2.23 on 2025-11-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_alter_lesson_youtube_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='kind',
            field=models.CharField(choices=[('course', 'Curso'), ('training', 'Capacitación')], default='course', help_text='Diferencia si es Curso o Capacitación.', max_length=20),
        ),
    ]
