# Generated by Django 4.2.23 on 2025-11-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_course_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('mp', 'Mercado Pago'), ('transfer', 'Transferencia')], default='', help_text='Método elegido por el usuario en el checkout.', max_length=12),
        ),
        migrations.AddField(
            model_name='purchase',
            name='transfer_receipt',
            field=models.FileField(blank=True, help_text='Comprobante de pago en caso de transferencia.', null=True, upload_to='receipts/'),
        ),
    ]
