# Generated by Django 5.2.6 on 2026-03-03 23:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='ShippingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_rate_ars', models.DecimalField(decimal_places=2, default=500, max_digits=10, verbose_name='Tarifa base (ARS)')),
                ('per_kg_ars', models.DecimalField(decimal_places=2, default=150, max_digits=8, verbose_name='$ por kg')),
                ('free_over_ars', models.DecimalField(decimal_places=2, default=15000, max_digits=12, verbose_name='Envío gratis desde (ARS)')),
                ('provider_name', models.CharField(blank=True, default='Andreani', max_length=100, verbose_name='Proveedor')),
                ('provider_url', models.URLField(blank=True, verbose_name='URL del proveedor')),
                ('provider_api_key', models.CharField(blank=True, max_length=255, verbose_name='API Key')),
                ('provider_active', models.BooleanField(default=False, verbose_name='Integración activa')),
            ],
            options={
                'verbose_name': 'Configuración de envíos',
            },
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Zona')),
                ('multiplier', models.DecimalField(decimal_places=2, default=1, max_digits=4, verbose_name='Multiplicador')),
                ('postal_codes', models.TextField(blank=True, help_text='Ej: 1000,1001,1002,1100', verbose_name='Códigos postales (separados por coma)')),
            ],
            options={
                'verbose_name': 'Zona de envío',
                'verbose_name_plural': 'Zonas de envío',
                'ordering': ['multiplier'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('price_ars', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio (ARS)')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Stock')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagen')),
                ('image_url', models.URLField(blank=True, verbose_name='URL de imagen (alternativa)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('weight_kg', models.DecimalField(decimal_places=3, default=0, max_digits=6, verbose_name='Peso (kg)')),
                ('width_cm', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Ancho (cm)')),
                ('height_cm', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Alto (cm)')),
                ('depth_cm', models.DecimalField(decimal_places=1, default=0, max_digits=6, verbose_name='Prof. (cm)')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='lms.productcategory')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StoreOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('shipped', 'Enviado'), ('delivered', 'Entregado'), ('cancelled', 'Cancelado')], default='pending', max_length=12)),
                ('payment_method', models.CharField(blank=True, choices=[('mp', 'Mercado Pago'), ('transfer', 'Transferencia'), ('cash', 'Efectivo')], max_length=12)),
                ('recipient_name', models.CharField(max_length=200, verbose_name='Destinatario')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('address', models.CharField(max_length=300, verbose_name='Dirección')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('province', models.CharField(max_length=100, verbose_name='Provincia')),
                ('postal_code', models.CharField(max_length=12, verbose_name='Código postal')),
                ('subtotal_ars', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('shipping_ars', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_ars', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tracking_number', models.CharField(blank=True, max_length=100, verbose_name='Número de seguimiento')),
                ('tracking_url', models.URLField(blank=True, verbose_name='URL de seguimiento')),
                ('notes', models.TextField(blank=True, verbose_name='Notas internas')),
                ('transfer_receipt', models.FileField(blank=True, null=True, upload_to='store_receipts/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido tienda',
                'verbose_name_plural': 'Pedidos tienda',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lms.storeorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='lms.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
