# Generated by Django 5.2.9 on 2026-04-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0007_productcategory_shippingconfig_shippingzone_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='depth_cm',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='Prof. (cm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height_cm',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='Alto (cm)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight_kg',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=8, verbose_name='Peso (kg)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width_cm',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=8, verbose_name='Ancho (cm)'),
        ),
    ]
