# Generated by Django 5.2.9 on 2026-08-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0011_stage_pdf_file_lesson_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('percent', models.PositiveIntegerField(default=10, verbose_name='Descuento (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('valid_until', models.DateField(blank=True, help_text='Dejar vacío para que no venza nunca.', null=True, verbose_name='Válido hasta')),
            ],
            options={
                'verbose_name': 'Código de descuento',
                'verbose_name_plural': 'Códigos de descuento',
                'ordering': ['code'],
            },
        ),
    ]
